# Generated by Django 4.2.1 on 2023-05-05 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0002_rename_request_requestfriend'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requestfriend',
            old_name='is_canceled',
            new_name='is_accepted',
        ),
    ]
