# Generated by Django 4.2.1 on 2023-05-05 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0003_rename_is_canceled_requestfriend_is_accepted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requestfriend',
            old_name='is_accepted',
            new_name='is_canceled',
        ),
    ]
